In [3]:
import math
math.pi*2

6.283185307179586

In [1]:
tpl =("Aamol", 2403, math.pi)

NameError: name 'math' is not defined

In [3]:
import math
tpl = ("Aamol Gote", 2403, math.pi)

In [7]:
print(tpl[0])
print(tpl[1])
print(tpl[2])
print(tpl)

Aamol Gote
2403
3.141592653589793
('Aamol Gote', 2403, 3.141592653589793)

In [9]:
short_tpl=("Test",,,,,)
print(len(short_tpl))

SyntaxError: invalid syntax (<ipython-input-9-934633562af5>, line 1)

In [1]:
first_str = "Aamol GOte"
second_str = "Shravani Gote"
print(1, first_str.split(' '))
print(1, first_str.upper())

1 ['Aamol', 'GOte']
1 AAMOL GOTE

In [2]:
print(3, first_str.replace('a', 's'))

3 Asmol GOte

In [3]:
print(first_str.replace('Aamol', 'Person'))

Person GOte

In [12]:
multiline = '''aamol gote
2403 Quail Ridge Dr
plainsboro, nj 08536'''
print(multiline.splitlines()[2])

plainsboro, nj 08536

In [16]:
long_str = "TESNSNSNSNSwewerewrewrwerewrewrwerewrwerw"
"TESTsferwerewr"
"wrewrwerwerwe"
print(long_str[1:5])

ESNS

In [20]:
city = ['New York', 'Seattle']
state = ['NJ', 'MA']
city_states = zip(city, state)
print(1, city_states)
print(2, list(city_states))

1 <zip object at 0x0000015EDB157908>
2 [('New York', 'NJ'), ('Seattle', 'MA')]

In [24]:
names = ['Aamol', 'Sharvani', 'Rohini']
names.append('Naitik')
print(1, names[0])
print(2, names[3])
print(3, names[-1])
print(4, names[-2])
print(5, names[-4])
print(6, len(names))

1 Aamol
2 Naitik
3 Naitik
4 Rohini
5 Aamol
6 4

In [25]:
for name in names:
    print(name)

Aamol
Sharvani
Rohini
Naitik

In [27]:
names_str=''
for name in names:
    names_str += name + ' '
print(names_str)

Aamol Sharvani Rohini Naitik

In [31]:
airports = { 'EWR': 'Newark Airport', 'JFK': 'John F Kennedy NY', 'TRT': 'TRENTON'}
airports['SFO'] = 'San Francisco Airport'
airports['OWR'] = 'Chicago Airport'
for code in airports:
    print(airports[code])
    
if 'OWR' in airports:
    print('Chicago airport found')
    
del airports['OWR']

if 'OWR' not in airports:
    print('Chicago airport not found')
    
print(airports['EWR'])

Newark Airport
John F Kennedy NY
TRENTON
San Francisco Airport
Chicago Airport
Chicago airport found
Chicago airport not found
Newark Airport

In [18]:
# Adding 2 Lists
import numpy as np;
lx = np.array([1, 12, 3])
ly = np.array([4, 5, 6])
lsum = []
lsum = lx + ly
print(lsum) 
print (lx > ly)
print(lsum + 1)

[ 5 17  9]
[False  True False]
[ 6 18 10]

In [25]:
# . Download and read in this flights.csv file. Can you figure out how to read in the first line to see the
# titles? Try reading in the first 1,000 lines and only the first 6 columns (check out the documentation for read_csv).
import pandas
flights = pandas.read_csv("file_excercises/flights.csv")
print(flights.columns)
flights = pandas.read_csv("file_excercises/flights.csv", usecols=[0,1,2,3,4,5], nrows=1000)
print(flights)

Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour'],
      dtype='object')
     year  month  day  dep_time  sched_dep_time  dep_delay
0    2013      1    1     517.0             515        2.0
1    2013      1    1     533.0             529        4.0
2    2013      1    1     542.0             540        2.0
3    2013      1    1     544.0             545       -1.0
4    2013      1    1     554.0             600       -6.0
5    2013      1    1     554.0             558       -4.0
6    2013      1    1     555.0             600       -5.0
7    2013      1    1     557.0             600       -3.0
8    2013      1    1     557.0             600       -3.0
9    2013      1    1     558.0             600       -2.0
10   2013      1    1     558.0             600       -2.0
11   2013      1    1     558.0             600       -2.0
12   2013      1    1     558.0             600       -2.0
13   2013      1    1     558.0             600       -2.0
14   2013      1    1     559.0             600       -1.0
15   2013      1    1     559.0             559        0.0
16   2013      1    1     559.0             600       -1.0
17   2013      1    1     600.0             600        0.0
18   2013      1    1     600.0             600        0.0
19   2013      1    1     601.0             600        1.0
20   2013      1    1     602.0             610       -8.0
21   2013      1    1     602.0             605       -3.0
22   2013      1    1     606.0             610       -4.0
23   2013      1    1     606.0             610       -4.0
24   2013      1    1     607.0             607        0.0
25   2013      1    1     608.0             600        8.0
26   2013      1    1     611.0             600       11.0
27   2013      1    1     613.0             610        3.0
28   2013      1    1     615.0             615        0.0
29   2013      1    1     615.0             615        0.0
..    ...    ...  ...       ...             ...        ...
970  2013      1    2     741.0             743       -2.0
971  2013      1    2     741.0             740        1.0
972  2013      1    2     743.0             745       -2.0
973  2013      1    2     744.0             730       14.0
974  2013      1    2     745.0             730       15.0
975  2013      1    2     745.0             746       -1.0
976  2013      1    2     747.0             749       -2.0
977  2013      1    2     750.0             725       25.0
978  2013      1    2     751.0             800       -9.0
979  2013      1    2     752.0             800       -8.0
980  2013      1    2     752.0             800       -8.0
981  2013      1    2     752.0             745        7.0
982  2013      1    2     754.0             635       79.0
983  2013      1    2     754.0             755       -1.0
984  2013      1    2     755.0             800       -5.0
985  2013      1    2     755.0             800       -5.0
986  2013      1    2     755.0             759       -4.0
987  2013      1    2     757.0             800       -3.0
988  2013      1    2     757.0             759       -2.0
989  2013      1    2     758.0             755        3.0
990  2013      1    2     759.0             805       -6.0
991  2013      1    2     800.0             810      -10.0
992  2013      1    2     801.0             730       31.0
993  2013      1    2     801.0             810       -9.0
994  2013      1    2     804.0             805       -1.0
995  2013      1    2     806.0             810       -4.0
996  2013      1    2     807.0             810       -3.0
997  2013      1    2     808.0             810       -2.0
998  2013      1    2     808.0             815       -7.0
999  2013      1    2     809.0             810       -1.0

[1000 rows x 6 columns]

In [34]:
import pandas;
fbdata = pandas.read_fwf("file_excercises/facebook.tsv", colspecs=[(0,8), (8,11), (11,14), (14, 18)])
print(fbdata)

       userid\ta   ge   dob  _day
0        2094382   14    19  1999
1        1192601   14  2\t1   999
2        2083884   14    16  1999
3        1203168   14    25  1999
4        1733186   14  4\t1   999
5        1524765   14  1\t1   999
6        1136133   13    14  2000
7        1680361   13  4\t2     0
8        1365174   13  1\t2     0
9        1712567   13  2\t2     0
10       1612453   13    22  2000
11       2104073   13  1\t2     0
12       1918584   13  5\t2     0
13       1704433   13    21  2000
14       1932519   13    28  2000
15       1751722   13  7\t2     0
16       1470850   13    30  2000
17       1001768   13    23  2000
18       1537661   13    16  2000
19       1020296   13    13  2000
20       1472643   13    13  2000
21       2041297   13    22  2000
22       1514978   13  2\t2     0
23       1708962   15    17  1998
24       1098955   15  3\t1   998
25       1001243   15    11  1998
26       2113084   15    24  1998
27       2163454   15    15  1998
28       1670750   15    28  1998
29       1041376   15    11  1998
...          ...  ...   ...   ...
98973    1836366   26  3\t1   987
98974    1686646   43  1\t1   970
98975    1749991  107    29   190
98976    1963699   18    17  1995
98977    1390362   17  5\t1   996
98978    1638976   18    15  1995
98979    1991657   15    13  1998
98980    1184126   15    20  1998
98981    1277820   17    27  1996
98982    1364616   18    23  1995
98983    1757787   18    26  1995
98984    1674381   18    25  1995
98985    1299870   18    16  1995
98986    1043082   18    24  1995
98987    1364887   20    29  1993
98988    1729341   21    20  1992
98989    1008872   25  5\t1   988
98990    1902600   58    11  1955
98991    1099760   15    29  1998
98992    1422393   19    27  1994
98993    1654565   19    15  1994
98994    2063006   20  4\t1   993
98995    1132164   20  9\t1   993
98996    1668695   24    25  1989
98997    1458985   28    14  1985
98998    1268299   68  4\t1   945
98999    1256153   18    12  1995
99000    1195943   15    10  1998
99001    1468023   23    11  1990
99002    1397896   39    15  1974

[99003 rows x 4 columns]

In [39]:
#What spreadsheets are in this mydata.xlsx file? Practice reading in the different spreadsheets.
#
import pandas
xlsx = pandas.ExcelFile("file_excercises/mydata.xlsx")
print(xlsx.sheet_names)
df = pandas.read_excel(xlsx, "Sheet2")
print(df)

['PICK_ME_FIRST!', 'Sheet2', 'extra_header', 'functions', 'date_time', 'unique_NA']
   variable 4 variable 5
0      Dayton     johnny
1    Columbus      amber
2   Cleveland       tony
3  Cincinnati      alice

In [46]:
import pandas
xlsx = pandas.ExcelFile("file_excercises/PEW Middle Class Data.xlsx")
print(xlsx.sheet_names)
df = pandas.read_excel(xlsx, "3. Median HH income, metro",index_col=[0,1,2,3,4,5,6,7,8], skiprows=6)
print(df)

['1. Distribution, metro', '2. Distribution, state', '3. Median HH income, metro', '4. Median HH income, state', '5. Income inequality, metro', '6. Demographics, metro', '7. Unemployment, metro', '8. Sectors, metro', '9. Cost of living, metro', 'BEA Regions']
                                                                                                                                                        Unnamed: 9  \
Metro                                        All_1999     Lower_1999   Middle_1999  Upper_1999    All_2014     Lower_2014   Middle_2014  Upper_2014
Akron, OH                                    77688.321261 27587.967763 81671.303980 180745.029083 68190.978858 25969.676988 75771.610987 173668.542912         NaN
Albany-Schenectady-Troy, NY                  73185.155486 27322.455118 79718.212201 177674.039447 76767.678765 24641.592391 77119.995220 163299.308983         NaN
Albuquerque, NM                              66067.179761 26426.871904 76363.590689 186766.840259 58864.751285 21442.494549 71643.163964 178378.041019         NaN
Allentown-Bethlehem-Easton, PA-NJ            71607.732477 29007.445790 78782.434578 180202.551072 69499.993576 25739.851167 76530.145317 169740.979142         NaN
Amarillo, TX                                 60599.323737 27014.159601 76296.730243 183931.107573 63254.270326 25958.557222 71626.155225 162210.004910         NaN
Anchorage, AK                                76652.961134 27813.286000 81361.665394 173445.885482 77459.667704 24474.622693 79652.790436 173913.039204         NaN
Ann Arbor, MI                                83377.930282 25528.920005 82355.317106 182023.216190 70566.347977 23632.811359 74154.481750 177262.686902         NaN
Anniston-Oxford-Jacksonville, AL             60515.735971 26245.191220 77661.850581 185581.593567 57055.797421 21180.885595 74870.130503 178092.304598         NaN
Atlanta-Sandy Springs-Roswell, GA            83530.747180 26982.145706 82649.156310 186041.191976 69136.488073 23651.950521 73684.940097 178754.190493         NaN
Atlantic City-Hammonton, NJ                  62551.170125 27380.060593 75697.916567 178081.648854 61133.443394 24123.276186 73978.020414 161652.734883         NaN
Auburn-Opelika, AL                           61621.839236 21209.388470 81473.628557 182023.851096 57785.926119 21122.567444 74332.172842 159387.524196         NaN
Augusta-Richmond County, GA-SC               68549.660728 25710.185559 78205.500726 180183.577161 63485.100737 22574.459034 74604.087499 170837.609790         NaN
Austin-Round Rock, TX                        77997.324942 26367.898940 80947.755769 189164.732262 74452.567694 22286.765395 75481.249989 178189.836379         NaN
Bakersfield, CA                              54270.047307 24879.826688 75657.990772 182597.634839 50880.100985 21812.235435 69949.599325 164720.040979         NaN
Baltimore-Columbia-Towson, MD                74760.038872 26206.217783 80708.689385 180067.169658 76546.547838 22977.940269 78685.665227 171151.457396         NaN
Bangor, ME                                   58848.107526 26146.585493 74842.161472 172849.757945 59917.353201 24066.205112 74648.705127 160051.886924         NaN
Barnstable Town, MA                          73015.415911 28838.194604 78374.800751 186052.937730 80965.892794 27149.515357 77832.508960 170645.404112         NaN
Baton Rouge, LA                              64554.126414 23810.938660 78572.109882 178283.866293 65846.492205 21612.911028 75268.813958 164616.239174         NaN
Beaumont-Port Arthur, TX                     62537.617332 24539.639374 76479.973773 175971.613290 54365.039171 23081.291741 70139.570658 164558.232792         NaN
Bellingham, WA                               63495.152682 27562.302925 74829.756393 186348.877006 61584.746552 24182.702850 75570.918259 161565.422202         NaN
Bend-Redmond, OR                             69792.757090 28953.014843 76742.922376 196525.583806 63544.267593 26707.825081 70902.937410 174936.300180         NaN
Binghamton, NY                               63455.055950 27816.484947 75314.726607 187644.182145 57953.224906 21855.536705 71030.468311 172571.825661         NaN
Birmingham-Hoover, AL                        70026.036066 25538.614525 80320.029468 187202.922741 61295.355503 23237.903775 74167.645336 167829.280024         NaN
Blacksburg-Christiansburg-Radford, VA        64598.765163 25989.324256 79634.673273 183106.682628 58258.100489 20805.411621 70615.884630 172546.156668         NaN
Bloomington, IL                              82618.265709 28285.606941 83562.687816 182100.088609 73861.436074 23454.150319 73861.436074 163499.516736         NaN
Boise City, ID                               71025.450767 28917.508967 77121.057511 182093.300003 60356.566645 24815.213164 71130.909937 173753.777132         NaN
Boston-Cambridge-Newton, MA-NH               78529.986336 25268.999412 82126.384791 187920.878898 79624.904418 22529.113944 78090.653813 178046.699700         NaN
Bremerton-Silverdale, WA                     70305.516635 28668.113156 76750.174952 175763.779378 68653.401783 22922.635887 75775.906473 168446.288484         NaN
Bridgeport-Stamford-Norwalk, CT              81924.460385 25963.757095 79813.765496 224066.910426 80293.753158 23801.357223 76852.583896 205191.174789         NaN
Brownsville-Harlingen, TX                    42674.326451 23228.974402 72590.517536 193305.928577 41219.968657 20305.403194 68918.821248 160810.577139         NaN
...                                                                                                                                                            ...
Spokane-Spokane Valley, WA                   64194.134929 27235.253273 76896.862569 183384.111964 57916.020455 24071.349303 70947.122026 158858.884969         NaN
Springfield, IL                              76784.142403 29325.216052 81310.726427 176208.213310 73325.297067 20722.359785 77190.801457 177999.795764         NaN
Springfield, MA                              68095.092725 25221.698944 79608.690981 174611.694294 62290.643859 23481.863131 74611.396753 164991.539943         NaN
Springfield, MO                              63717.149873 28819.391630 74456.163275 188609.678235 56145.604722 24326.549669 70182.005902 161011.287187         NaN
Springfield, OH                              73894.882289 28046.271942 79378.537695 173265.303673 53957.071924 25618.261200 72653.140110 171245.092063         NaN
State College, PA                            58926.762564 26189.685817 76304.715402 174832.104222 57578.599637 18113.267730 73689.097019 176768.879217         NaN
Stockton-Lodi, CA                            61852.505331 25269.878512 77487.446891 178169.558862 54038.409030 22704.137678 72973.881279 165650.689198         NaN
Syracuse, NY                                 67120.268406 26542.888696 78811.908850 176597.044163 65932.921541 23602.361906 75471.706389 160132.998864         NaN
Tampa-St. Petersburg-Clearwater, FL          64522.918361 28290.832702 74697.696024 188853.652929 57150.661844 24617.984538 69849.244301 172334.707906         NaN
Toledo, OH                                   71680.307074 26478.909746 80189.214492 177399.711381 61487.803669 23382.685902 73000.000605 165507.084866         NaN
Trenton, NJ                                  80150.387571 26423.208987 82572.528085 188913.260799 76700.250027 21831.461199 76410.114196 180109.537571         NaN
Tucson, AZ                                   62936.728771 26879.803805 75544.293827 195355.574849 56963.652318 23141.480507 71495.905004 169110.824417         NaN
Tyler, TX                                    64738.713013 26172.641043 76248.916966 189874.752099 53283.512006 24831.148031 68861.369123 169181.301564         NaN
Urban Honolulu, HI                           64576.348111 26206.242202 77702.215927 173204.670186 66938.775406 23995.000504 75220.489740 161045.373947         NaN
Utica-Rome, NY                               61963.687072 26806.618722 75297.657414 175241.300893 60774.822274 25224.046436 72168.287127 160533.431690         NaN
Vallejo-Fairfield, CA                        69652.784820 28386.385998 78871.541139 171468.764967 64347.817924 22591.970068 75155.936206 156863.198708         NaN
Virginia Beach-Norfolk-Newport News, VA-NC   68433.521839 27676.195225 77371.478938 177197.225328 70123.514547 24304.154252 75368.909174 166543.353543         NaN
Visalia-Porterville, CA                      50740.362780 25270.391321 74521.851587 185660.004411 43933.053042 21904.276615 67991.637131 168494.474137         NaN
Waco, TX                                     59911.891889 25633.777109 74250.673630 183660.344746 56975.360982 22980.053371 70459.515083 161150.647995         NaN
Washington-Arlington-Alexandria, DC-VA-MD-WV 85930.421803 26949.863198 82917.257417 187072.986864 87610.888397 23372.293597 79383.508497 177903.874790         NaN
Wausau, WI                                   75502.292379 28934.163030 80082.281734 180455.780735 69074.549937 28178.699947 75143.205633 154982.849710         NaN
Wichita, KS                                  74893.686505 28331.002692 80239.152260 175344.253281 65717.419779 26028.185665 73986.836552 167815.527541         NaN
Wichita Falls, TX                            59303.237176 27779.440646 74514.305978 179294.074390 62637.365790 22840.224910 76134.094580 157467.199466         NaN
Winston-Salem, NC                            73097.685027 26775.703703 80077.422264 179676.873639 58693.243614 23017.292464 71884.248116 161536.115902         NaN
Worcester, MA-CT                             70347.664600 26072.912022 80333.753198 172179.615065 71277.614641 23959.199013 77915.474194 166475.890164         NaN
Yakima, WA                                   55655.386946 25546.086876 74107.966383 178260.448044 51152.604538 24358.384763 66757.585571 170745.360764         NaN
York-Hanover, PA                             73941.669950 30450.390904 78812.739111 171113.388757 67849.678246 26463.692520 74489.027364 159455.351306         NaN
Youngstown-Warren-Boardman, OH-PA            67411.787763 27712.726717 78641.876242 170716.865779 58682.816668 23432.482363 71800.157049 159479.184325         NaN
Yuba City, CA                                53568.842890 26552.070408 71858.666713 180958.845760 50401.535347 25218.936886 68110.178688 164578.965440         NaN
Yuma, AZ                                     52888.541520 27390.560955 72103.789121 180115.007355 45510.674199 22626.870891 64896.393055 174963.545339         NaN

                                                                                                                                                        Unnamed: 10
Metro                                        All_1999     Lower_1999   Middle_1999  Upper_1999    All_2014     Lower_2014   Middle_2014  Upper_2014
Akron, OH                                    77688.321261 27587.967763 81671.303980 180745.029083 68190.978858 25969.676988 75771.610987 173668.542912          NaN
Albany-Schenectady-Troy, NY                  73185.155486 27322.455118 79718.212201 177674.039447 76767.678765 24641.592391 77119.995220 163299.308983          NaN
Albuquerque, NM                              66067.179761 26426.871904 76363.590689 186766.840259 58864.751285 21442.494549 71643.163964 178378.041019          NaN
Allentown-Bethlehem-Easton, PA-NJ            71607.732477 29007.445790 78782.434578 180202.551072 69499.993576 25739.851167 76530.145317 169740.979142          NaN
Amarillo, TX                                 60599.323737 27014.159601 76296.730243 183931.107573 63254.270326 25958.557222 71626.155225 162210.004910          NaN
Anchorage, AK                                76652.961134 27813.286000 81361.665394 173445.885482 77459.667704 24474.622693 79652.790436 173913.039204          NaN
Ann Arbor, MI                                83377.930282 25528.920005 82355.317106 182023.216190 70566.347977 23632.811359 74154.481750 177262.686902          NaN
Anniston-Oxford-Jacksonville, AL             60515.735971 26245.191220 77661.850581 185581.593567 57055.797421 21180.885595 74870.130503 178092.304598          NaN
Atlanta-Sandy Springs-Roswell, GA            83530.747180 26982.145706 82649.156310 186041.191976 69136.488073 23651.950521 73684.940097 178754.190493          NaN
Atlantic City-Hammonton, NJ                  62551.170125 27380.060593 75697.916567 178081.648854 61133.443394 24123.276186 73978.020414 161652.734883          NaN
Auburn-Opelika, AL                           61621.839236 21209.388470 81473.628557 182023.851096 57785.926119 21122.567444 74332.172842 159387.524196          NaN
Augusta-Richmond County, GA-SC               68549.660728 25710.185559 78205.500726 180183.577161 63485.100737 22574.459034 74604.087499 170837.609790          NaN
Austin-Round Rock, TX                        77997.324942 26367.898940 80947.755769 189164.732262 74452.567694 22286.765395 75481.249989 178189.836379          NaN
Bakersfield, CA                              54270.047307 24879.826688 75657.990772 182597.634839 50880.100985 21812.235435 69949.599325 164720.040979          NaN
Baltimore-Columbia-Towson, MD                74760.038872 26206.217783 80708.689385 180067.169658 76546.547838 22977.940269 78685.665227 171151.457396          NaN
Bangor, ME                                   58848.107526 26146.585493 74842.161472 172849.757945 59917.353201 24066.205112 74648.705127 160051.886924          NaN
Barnstable Town, MA                          73015.415911 28838.194604 78374.800751 186052.937730 80965.892794 27149.515357 77832.508960 170645.404112          NaN
Baton Rouge, LA                              64554.126414 23810.938660 78572.109882 178283.866293 65846.492205 21612.911028 75268.813958 164616.239174          NaN
Beaumont-Port Arthur, TX                     62537.617332 24539.639374 76479.973773 175971.613290 54365.039171 23081.291741 70139.570658 164558.232792          NaN
Bellingham, WA                               63495.152682 27562.302925 74829.756393 186348.877006 61584.746552 24182.702850 75570.918259 161565.422202          NaN
Bend-Redmond, OR                             69792.757090 28953.014843 76742.922376 196525.583806 63544.267593 26707.825081 70902.937410 174936.300180          NaN
Binghamton, NY                               63455.055950 27816.484947 75314.726607 187644.182145 57953.224906 21855.536705 71030.468311 172571.825661          NaN
Birmingham-Hoover, AL                        70026.036066 25538.614525 80320.029468 187202.922741 61295.355503 23237.903775 74167.645336 167829.280024          NaN
Blacksburg-Christiansburg-Radford, VA        64598.765163 25989.324256 79634.673273 183106.682628 58258.100489 20805.411621 70615.884630 172546.156668          NaN
Bloomington, IL                              82618.265709 28285.606941 83562.687816 182100.088609 73861.436074 23454.150319 73861.436074 163499.516736          NaN
Boise City, ID                               71025.450767 28917.508967 77121.057511 182093.300003 60356.566645 24815.213164 71130.909937 173753.777132          NaN
Boston-Cambridge-Newton, MA-NH               78529.986336 25268.999412 82126.384791 187920.878898 79624.904418 22529.113944 78090.653813 178046.699700          NaN
Bremerton-Silverdale, WA                     70305.516635 28668.113156 76750.174952 175763.779378 68653.401783 22922.635887 75775.906473 168446.288484          NaN
Bridgeport-Stamford-Norwalk, CT              81924.460385 25963.757095 79813.765496 224066.910426 80293.753158 23801.357223 76852.583896 205191.174789          NaN
Brownsville-Harlingen, TX                    42674.326451 23228.974402 72590.517536 193305.928577 41219.968657 20305.403194 68918.821248 160810.577139          NaN
...                                                                                                                                                             ...
Spokane-Spokane Valley, WA                   64194.134929 27235.253273 76896.862569 183384.111964 57916.020455 24071.349303 70947.122026 158858.884969          NaN
Springfield, IL                              76784.142403 29325.216052 81310.726427 176208.213310 73325.297067 20722.359785 77190.801457 177999.795764          NaN
Springfield, MA                              68095.092725 25221.698944 79608.690981 174611.694294 62290.643859 23481.863131 74611.396753 164991.539943          NaN
Springfield, MO                              63717.149873 28819.391630 74456.163275 188609.678235 56145.604722 24326.549669 70182.005902 161011.287187          NaN
Springfield, OH                              73894.882289 28046.271942 79378.537695 173265.303673 53957.071924 25618.261200 72653.140110 171245.092063          NaN
State College, PA                            58926.762564 26189.685817 76304.715402 174832.104222 57578.599637 18113.267730 73689.097019 176768.879217          NaN
Stockton-Lodi, CA                            61852.505331 25269.878512 77487.446891 178169.558862 54038.409030 22704.137678 72973.881279 165650.689198          NaN
Syracuse, NY                                 67120.268406 26542.888696 78811.908850 176597.044163 65932.921541 23602.361906 75471.706389 160132.998864          NaN
Tampa-St. Petersburg-Clearwater, FL          64522.918361 28290.832702 74697.696024 188853.652929 57150.661844 24617.984538 69849.244301 172334.707906          NaN
Toledo, OH                                   71680.307074 26478.909746 80189.214492 177399.711381 61487.803669 23382.685902 73000.000605 165507.084866          NaN
Trenton, NJ                                  80150.387571 26423.208987 82572.528085 188913.260799 76700.250027 21831.461199 76410.114196 180109.537571          NaN
Tucson, AZ                                   62936.728771 26879.803805 75544.293827 195355.574849 56963.652318 23141.480507 71495.905004 169110.824417          NaN
Tyler, TX                                    64738.713013 26172.641043 76248.916966 189874.752099 53283.512006 24831.148031 68861.369123 169181.301564          NaN
Urban Honolulu, HI                           64576.348111 26206.242202 77702.215927 173204.670186 66938.775406 23995.000504 75220.489740 161045.373947          NaN
Utica-Rome, NY                               61963.687072 26806.618722 75297.657414 175241.300893 60774.822274 25224.046436 72168.287127 160533.431690          NaN
Vallejo-Fairfield, CA                        69652.784820 28386.385998 78871.541139 171468.764967 64347.817924 22591.970068 75155.936206 156863.198708          NaN
Virginia Beach-Norfolk-Newport News, VA-NC   68433.521839 27676.195225 77371.478938 177197.225328 70123.514547 24304.154252 75368.909174 166543.353543          NaN
Visalia-Porterville, CA                      50740.362780 25270.391321 74521.851587 185660.004411 43933.053042 21904.276615 67991.637131 168494.474137          NaN
Waco, TX                                     59911.891889 25633.777109 74250.673630 183660.344746 56975.360982 22980.053371 70459.515083 161150.647995          NaN
Washington-Arlington-Alexandria, DC-VA-MD-WV 85930.421803 26949.863198 82917.257417 187072.986864 87610.888397 23372.293597 79383.508497 177903.874790          NaN
Wausau, WI                                   75502.292379 28934.163030 80082.281734 180455.780735 69074.549937 28178.699947 75143.205633 154982.849710          NaN
Wichita, KS                                  74893.686505 28331.002692 80239.152260 175344.253281 65717.419779 26028.185665 73986.836552 167815.527541          NaN
Wichita Falls, TX                            59303.237176 27779.440646 74514.305978 179294.074390 62637.365790 22840.224910 76134.094580 157467.199466          NaN
Winston-Salem, NC                            73097.685027 26775.703703 80077.422264 179676.873639 58693.243614 23017.292464 71884.248116 161536.115902          NaN

In [33]:
import pandas
customers = pandas.read_csv("file_excercises/CustomerData_Merrimack.csv")
print(customers.columns)

Index(['CustomerID', 'Region', 'TownSize', 'Gender', 'Age', 'EducationYears',
       'JobCategory', 'UnionMember', 'EmploymentLength', 'Retired', 'HHIncome',
       'DebtToIncomeRatio', 'CreditDebt', 'OtherDebt', 'LoanDefault',
       'MaritalStatus', 'HouseholdSize', 'NumberPets', 'NumberCats',
       'NumberDogs', 'NumberBirds', 'HomeOwner', 'CarsOwned', 'CarOwnership',
       'CarBrand', 'CarValue', 'CommuteTime', 'PoliticalPartyMem', 'Votes',
       'CreditCard', 'CardTenure', 'CardItemsMonthly', 'CardSpendMonth',
       'ActiveLifestyle', 'PhoneCoTenure', 'VoiceLastMonth', 'VoiceOverTenure',
       'EquipmentRental', 'EquipmentLastMonth', 'EquipmentOverTenure',
       'CallingCard', 'WirelessData', 'DataLastMonth', 'DataOverTenure',
       'Multiline', 'VM', 'Pager', 'Internet', 'CallerID', 'CallWait',
       'CallForward', 'ThreeWayCalling', 'EBilling', 'TVWatchingHours',
       'OwnsPC', 'OwnsMobileDevice', 'OwnsGameSystem', 'OwnsFax',
       'NewsSubscriber'],
      dtype='object')

In [43]:
customers.query('Gender == "Female" & Age > 45 & (Region == 3 | Region == 4)').loc[1:10, 'Gender': 'Retired']

,Gender,Age,EducationYears,JobCategory,UnionMember,EmploymentLength,Retired
2,Female,67,14,Sales,No,16,No
10,Female,59,19,Professional,No,8,No

In [42]:
customers.loc[1:10, 'Gender': 'Retired']

,Gender,Age,EducationYears,JobCategory,UnionMember,EmploymentLength,Retired
1,Male,22,17,Sales,No,0,No
2,Female,67,14,Sales,No,16,No
3,Male,23,16,Sales,No,0,No
4,Male,26,16,Sales,No,1,No
5,Male,64,17,Service,No,22,No
6,Female,52,14,Professional,No,10,No
7,Female,44,16,Professional,No,11,No
8,Female,66,12,Professional,No,15,Yes
9,Male,47,11,Labor,No,19,No
10,Female,59,19,Professional,No,8,No

In [72]:
import numpy
import pandas
customers['CarBrand'].replace('-1', numpy.nan, inplace=True)
customers['CarOwnership'].replace('-1', numpy.nan, inplace=True)
series = numpy.sum(customers.isnull())
pandas.DataFrame(series).rename({0:'Count'}, axis="columns").query('Count > 0').sort_values('Count', ascending=False)

               Count
CarOwnership     497
CarBrand         497
NumberBirds       34
Gender            33
JobCategory       15
HomeOwner         13
HouseholdSize      8
NumberDogs         8
NumberCats         7
NumberPets         6

In [76]:
import pandas
nycflights = pandas.read_csv("file_excercises/nycflights.csv")
#What are the dimensions of this data set? What are the names of all the variables?
print(nycflights.shape)
print(nycflights.columns)

(336776, 19)
Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour'],
      dtype='object')

In [77]:
nycflights

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T05:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T05:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T05:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T05:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T06:00:00Z
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01T05:00:00Z
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,2013-01-01T06:00:00Z
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,2013-01-01T06:00:00Z
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,2013-01-01T06:00:00Z
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,2013-01-01T06:00:00Z
10,2013,1,1,558.0,600,-2.0,849.0,851,-2.0,B6,49,N793JB,JFK,PBI,149.0,1028,6,0,2013-01-01T06:00:00Z
11,2013,1,1,558.0,600,-2.0,853.0,856,-3.0,B6,71,N657JB,JFK,TPA,158.0,1005,6,0,2013-01-01T06:00:00Z
12,2013,1,1,558.0,600,-2.0,924.0,917,7.0,UA,194,N29129,JFK,LAX,345.0,2475,6,0,2013-01-01T06:00:00Z
13,2013,1,1,558.0,600,-2.0,923.0,937,-14.0,UA,1124,N53441,EWR,SFO,361.0,2565,6,0,2013-01-01T06:00:00Z
14,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,707,N3DUAA,LGA,DFW,257.0,1389,6,0,2013-01-01T06:00:00Z
15,2013,1,1,559.0,559,0.0,702.0,706,-4.0,B6,1806,N708JB,JFK,BOS,44.0,187,5,59,2013-01-01T05:00:00Z
16,2013,1,1,559.0,600,-1.0,854.0,902,-8.0,UA,1187,N76515,EWR,LAS,337.0,2227,6,0,2013-01-01T06:00:00Z
17,2013,1,1,600.0,600,0.0,851.0,858,-7.0,B6,371,N595JB,LGA,FLL,152.0,1076,6,0,2013-01-01T06:00:00Z
18,2013,1,1,600.0,600,0.0,837.0,825,12.0,MQ,4650,N542MQ,LGA,ATL,134.0,762,6,0,2013-01-01T06:00:00Z
19,2013,1,1,601.0,600,1.0,844.0,850,-6.0,B6,343,N644JB,EWR,PBI,147.0,1023,6,0,2013-01-01T06:00:00Z
20,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,1919,N971DL,LGA,MSP,170.0,1020,6,10,2013-01-01T06:00:00Z
21,2013,1,1,602.0,605,-3.0,821.0,805,16.0,MQ,4401,N730MQ,LGA,DTW,105.0,502,6,5,2013-01-01T06:00:00Z
22,2013,1,1,606.0,610,-4.0,858.0,910,-12.0,AA,1895,N633AA,EWR,MIA,152.0,1085,6,10,2013-01-01T06:00:00Z
23,2013,1,1,606.0,610,-4.0,837.0,845,-8.0,DL,1743,N3739P,JFK,ATL,128.0,760,6,10,2013-01-01T06:00:00Z
24,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,1077,N53442,EWR,MIA,157.0,1085,6,7,2013-01-01T06:00:00Z
25,2013,1,1,608.0,600,8.0,807.0,735,32.0,MQ,3768,N9EAMQ,EWR,ORD,139.0,719,6,0,2013-01-01T06:00:00Z
26,2013,1,1,611.0,600,11.0,945.0,931,14.0,UA,303,N532UA,JFK,SFO,366.0,2586,6,0,2013-01-01T06:00:00Z
27,2013,1,1,613.0,610,3.0,925.0,921,4.0,B6,135,N635JB,JFK,RSW,175.0,1074,6,10,2013-01-01T06:00:00Z
28,2013,1,1,615.0,615,0.0,1039.0,1100,-21.0,B6,709,N794JB,JFK,SJU,182.0,1598,6,15,2013-01-01T06:00:00Z
29,2013,1,1,615.0,615,0.0,833.0,842,-9.0,DL,575,N326NB,EWR,ATL,120.0,746,6,15,2013-01-01T06:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336746,2013,9,30,2123.0,2125,-2.0,2223.0,2247,-24.0,EV,5489,N712EV,LGA,CHO,45.0,305,21,25,2013-09-30T21:00:00Z
336747,2013,9,30,2127.0,2129,-2.0,2314.0,2323,-9.0,EV,3833,N16546,EWR,CLT,72.0,529,21,29,2013-09-30T21:00:00Z
336748,2013,9,30,2128.0,2130,-2.0,2328.0,2359,-31.0,B6,97,N807JB,JFK,DEN,213.0,1626,21,30,2013-09-30T21:00:00Z
336749,2013,9,30,2129.0,2059,30.0,2230.0,2232,-2.0,EV,5048,N751EV,LGA,RIC,45.0,292,20,59,2013-09-30T20:00:00Z
336750,2013,9,30,2131.0,2140,-9.0,2225.0,2255,-30.0,MQ,3621,N807MQ,JFK,DCA,36.0,213,21,40,2013-09-30T21:00:00Z
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,2013-09-30T21:00:00Z
336752,2013,9,30,2142.0,2129,13.0,2250.0,2239,11.0,EV,4509,N12957,EWR,PWM,47.0,284,21,29,2013-09-30T21:00:00Z
336753,2013,9,30,2145.0,2145,0.0,115.0,140,-25.0,B6,1103,N633JB,JFK,SJU,192.0,1598,21,45,2013-09-30T21:00:00Z
336754,2013,9,30,2147.0,2137,10.0,30.0,27,3.0,B6,1371,N627JB,LGA,FLL,139.0,1076,21,37,2013-09-30T21:00:00Z
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,523,N813UA,EWR,BOS,37.0,200,21,56,2013-09-30T21:00:00Z
336756,2013,9,30,2150.0,2159,-9.0,2250.0,2306,-16.0,EV,3842,N10575,EWR,MHT,39.0,209,21,59,2013-09-30T21:00:00Z
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30T18:00:00Z
336758,2013,9,30,2203.0,2205,-2.0,2339.0,2331,8.0,EV,5311,N722EV,LGA,BGR,61.0,378,22,5,2013-09-30T22:00:00Z
336759,2013,9,30,2207.0,2140,27.0,2257.0,2250,7.0,MQ,3660,N532MQ,LGA,BNA,97.0,764,21,40,2013-09-30T21:00:00Z
336760,2013,9,30,2211.0,2059,72.0,2339.0,2242,57.0,EV,4672,N12145,EWR,STL,120.0,872,20,59,2013-09-30T20:00:00Z
336761,2013,9,30,2231.0,2245,-14.0,2335.0,2356,-21.0,B6,108,N193JB,JFK,PWM,48.0,273,22,45,2013-09-30T22:00:00Z
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-09-30T21:00:00Z
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-09-30T20:00:00Z
336764,2013,9,30,2237.0,2245,-8.0,2345.0,2353,-8.0,B6,234,N318JB,JFK,BTV,43.0,266,22,45,2013-09-30T22:00:00Z
336765,2013,9,30,2240.0,2245,-5.0,2334.0,2351,-17.0,B6,1816,N354JB,JFK,SYR,41.0,209,22,45,2013-09-30T22:00:00Z
336766,2013,9,30,2240.0,2250,-10.0,2347.0,7,-20.0,B6,2002,N281JB,JFK,BUF,52.0,301,22,50,2013-09-30T22:00:00Z
336767,2013,9,30,2241.0,2246,-5.0,2345.0,1,-16.0,B6,486,N346JB,JFK,ROC,47.0,264,22,46,2013-09-30T22:00:00Z
336768,2013,9,30,2307.0,2255,12.0,2359.0,2358,1.0,B6,718,N565JB,JFK,BOS,33.0,187,22,55,2013-09-30T22:00:00Z
336769,2013,9,30,2349.0,2359,-10.0,325.0,350,-25.0,B6,745,N516JB,JFK,PSE,196.0,1617,23,59,2013-09-30T23:00:00Z
336770,2013,9,30,NaN,1842,NaN,NaN,2019,NaN,EV,5274,N740EV,LGA,BNA,NaN,764,18,42,2013-09-30T18:00:00Z
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T14:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-09-30T22:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T12:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T11:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T08:00:00Z

In [78]:
pandas.DataFrame(numpy.sum(nycflights.isnull())).rename({0:'Count'}, axis="columns").query('Count > 0').sort_values('Count', ascending=False)

           Count
arr_delay   9430
air_time    9430
arr_time    8713
dep_time    8255
dep_delay   8255
tailnum     2512

In [82]:
nycflights.dropna(axis=0, how='any').shape

(327346, 19)

In [86]:
nycflights['time_hour'].dtype

dtype('O')

In [88]:
nycflights.query('month==12 & day==25')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
105232,2013,12,25,456.0,500,-4.0,649.0,651,-2.0,US,1895,N156UW,EWR,CLT,98.0,529,5,0,2013-12-25T05:00:00Z
105233,2013,12,25,524.0,515,9.0,805.0,814,-9.0,UA,1016,N32404,EWR,IAH,203.0,1400,5,15,2013-12-25T05:00:00Z
105234,2013,12,25,542.0,540,2.0,832.0,850,-18.0,AA,2243,N5EBAA,JFK,MIA,146.0,1089,5,40,2013-12-25T05:00:00Z
105235,2013,12,25,546.0,550,-4.0,1022.0,1027,-5.0,B6,939,N665JB,JFK,BQN,191.0,1576,5,50,2013-12-25T05:00:00Z
105236,2013,12,25,556.0,600,-4.0,730.0,745,-15.0,AA,301,N3JLAA,LGA,ORD,123.0,733,6,0,2013-12-25T06:00:00Z
105237,2013,12,25,557.0,600,-3.0,743.0,752,-9.0,DL,731,N369NB,LGA,DTW,88.0,502,6,0,2013-12-25T06:00:00Z
105238,2013,12,25,557.0,600,-3.0,818.0,831,-13.0,DL,904,N397DA,LGA,ATL,118.0,762,6,0,2013-12-25T06:00:00Z
105239,2013,12,25,559.0,600,-1.0,855.0,856,-1.0,B6,371,N608JB,LGA,FLL,147.0,1076,6,0,2013-12-25T06:00:00Z
105240,2013,12,25,559.0,600,-1.0,849.0,855,-6.0,B6,605,N536JB,EWR,FLL,149.0,1065,6,0,2013-12-25T06:00:00Z
105241,2013,12,25,600.0,600,0.0,850.0,846,4.0,B6,583,N746JB,JFK,MCO,137.0,944,6,0,2013-12-25T06:00:00Z
105242,2013,12,25,600.0,600,0.0,715.0,723,-8.0,EV,5747,N835AS,LGA,IAD,47.0,229,6,0,2013-12-25T06:00:00Z
105243,2013,12,25,601.0,600,1.0,855.0,905,-10.0,AA,1175,N3EJAA,LGA,MIA,152.0,1096,6,0,2013-12-25T06:00:00Z
105244,2013,12,25,601.0,600,1.0,846.0,849,-3.0,B6,353,N766JB,JFK,PBI,143.0,1028,6,0,2013-12-25T06:00:00Z
105245,2013,12,25,604.0,611,-7.0,1051.0,1055,-4.0,B6,1403,N779JB,JFK,SJU,190.0,1598,6,11,2013-12-25T06:00:00Z
105246,2013,12,25,605.0,600,5.0,912.0,937,-25.0,UA,303,N596UA,JFK,SFO,345.0,2586,6,0,2013-12-25T06:00:00Z
105247,2013,12,25,610.0,610,0.0,922.0,915,7.0,AA,1205,N5BTAA,EWR,MIA,145.0,1085,6,10,2013-12-25T06:00:00Z
105248,2013,12,25,610.0,605,5.0,718.0,723,-5.0,EV,6177,N11189,EWR,IAD,44.0,212,6,5,2013-12-25T06:00:00Z
105249,2013,12,25,611.0,611,0.0,908.0,912,-4.0,B6,601,N804JB,JFK,FLL,153.0,1069,6,11,2013-12-25T06:00:00Z
105250,2013,12,25,612.0,615,-3.0,859.0,852,7.0,DL,479,N3769L,JFK,ATL,127.0,760,6,15,2013-12-25T06:00:00Z
105251,2013,12,25,615.0,615,0.0,802.0,818,-16.0,US,1963,N169UW,EWR,CLT,87.0,529,6,15,2013-12-25T06:00:00Z
105252,2013,12,25,620.0,615,5.0,818.0,817,1.0,US,840,N151UW,JFK,CLT,96.0,541,6,15,2013-12-25T06:00:00Z
105253,2013,12,25,621.0,610,11.0,902.0,905,-3.0,UA,1627,N76269,EWR,PBI,142.0,1023,6,10,2013-12-25T06:00:00Z
105254,2013,12,25,627.0,625,2.0,1010.0,1009,1.0,US,690,N672AW,EWR,PHX,288.0,2133,6,25,2013-12-25T06:00:00Z
105255,2013,12,25,628.0,630,-2.0,932.0,938,-6.0,B6,929,N712JB,JFK,RSW,162.0,1074,6,30,2013-12-25T06:00:00Z
105256,2013,12,25,628.0,630,-2.0,949.0,919,30.0,B6,1099,N571JB,LGA,MCO,136.0,950,6,30,2013-12-25T06:00:00Z
105257,2013,12,25,630.0,631,-1.0,924.0,958,-34.0,UA,398,N505UA,JFK,LAX,335.0,2475,6,31,2013-12-25T06:00:00Z
105258,2013,12,25,632.0,635,-3.0,927.0,929,-2.0,B6,525,N556JB,JFK,TPA,151.0,1005,6,35,2013-12-25T06:00:00Z
105259,2013,12,25,632.0,620,12.0,922.0,919,3.0,UA,596,N556UA,EWR,TPA,147.0,997,6,20,2013-12-25T06:00:00Z
105260,2013,12,25,635.0,614,21.0,921.0,925,-4.0,UA,1701,N38417,EWR,FLL,151.0,1065,6,14,2013-12-25T06:00:00Z
105261,2013,12,25,643.0,630,13.0,904.0,859,5.0,DL,807,N977AT,EWR,ATL,115.0,746,6,30,2013-12-25T06:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105921,2013,12,25,2126.0,2129,-3.0,24.0,22,2.0,B6,2043,N599JB,EWR,PBI,144.0,1023,21,29,2013-12-25T21:00:00Z
105922,2013,12,25,2129.0,2053,36.0,1.0,2333,28.0,EV,4388,N17984,EWR,JAX,133.0,820,20,53,2013-12-25T20:00:00Z
105923,2013,12,25,2130.0,2135,-5.0,25.0,55,-30.0,AA,185,N332AA,JFK,LAX,328.0,2475,21,35,2013-12-25T21:00:00Z
105924,2013,12,25,2130.0,2115,15.0,2322.0,2315,7.0,MQ,3384,N520MQ,LGA,CLT,90.0,544,21,15,2013-12-25T21:00:00Z
105925,2013,12,25,2131.0,2046,45.0,24.0,2349,35.0,UA,236,N406UA,EWR,TPA,151.0,997,20,46,2013-12-25T20:00:00Z
105926,2013,12,25,2140.0,2141,-1.0,44.0,37,7.0,B6,425,N579JB,JFK,TPA,160.0,1005,21,41,2013-12-25T21:00:00Z
105927,2013,12,25,2144.0,2145,-1.0,27.0,19,8.0,B6,2227,N273JB,EWR,MCO,144.0,937,21,45,2013-12-25T21:00:00Z
105928,2013,12,25,2149.0,2155,-6.0,2328.0,2334,-6.0,B6,985,N339JB,JFK,RDU,80.0,427,21,55,2013-12-25T21:00:00Z
105929,2013,12,25,2150.0,2159,-9.0,103.0,45,18.0,B6,1183,N634JB,JFK,MCO,151.0,944,21,59,2013-12-25T21:00:00Z
105930,2013,12,25,2152.0,2155,-3.0,100.0,56,4.0,B6,1901,N665JB,JFK,FLL,154.0,1069,21,55,2013-12-25T21:00:00Z
105931,2013,12,25,2153.0,2155,-2.0,50.0,46,4.0,B6,2053,N613JB,JFK,PBI,148.0,1028,21,55,2013-12-25T21:00:00Z
105932,2013,12,25,2153.0,2135,18.0,22.0,19,3.0,B6,611,N519JB,JFK,LAS,305.0,2248,21,35,2013-12-25T21:00:00Z
105933,2013,12,25,2153.0,2030,83.0,46.0,2347,59.0,UA,1682,N78524,EWR,FLL,151.0,1065,20,30,2013-12-25T20:00:00Z
105934,2013,12,25,2203.0,2136,27.0,2327.0,2259,28.0,B6,702,N198JB,JFK,BUF,59.0,301,21,36,2013-12-25T21:00:00Z
105935,2013,12,25,2203.0,2130,33.0,2309.0,2245,24.0,MQ,3621,N844MQ,JFK,DCA,42.0,213,21,30,2013-12-25T21:00:00Z
105936,2013,12,25,2219.0,2110,69.0,102.0,2339,83.0,B6,775,N258JB,JFK,MSY,192.0,1182,21,10,2013-12-25T21:00:00Z
105937,2013,12,25,2231.0,2219,12.0,311.0,304,7.0,B6,1203,N618JB,JFK,SJU,194.0,1598,22,19,2013-12-25T22:00:00Z
105938,2013,12,25,2302.0,2245,17.0,15.0,3,12.0,B6,486,N203JB,JFK,ROC,54.0,264,22,45,2013-12-25T22:00:00Z
105939,2013,12,25,2308.0,2245,23.0,10.0,2355,15.0,B6,234,N316JB,JFK,BTV,43.0,266,22,45,2013-12-25T22:00:00Z
105940,2013,12,25,2312.0,2250,22.0,10.0,2356,14.0,B6,1816,N358JB,JFK,SYR,44.0,209,22,50,2013-12-25T22:00:00Z
105941,2013,12,25,2314.0,2245,29.0,15.0,2353,22.0,B6,108,N279JB,JFK,PWM,46.0,273,22,45,2013-12-25T22:00:00Z
105942,2013,12,25,2315.0,2330,-15.0,348.0,409,-21.0,B6,1389,N554JB,EWR,SJU,199.0,1608,23,30,2013-12-25T23:00:00Z
105943,2013,12,25,2352.0,2359,-7.0,429.0,440,-11.0,B6,1503,N531JB,JFK,SJU,198.0,1598,23,59,2013-12-25T23:00:00Z
105944,2013,12,25,2353.0,2355,-2.0,442.0,438,4.0,DL,2380,N713TW,JFK,SJU,196.0,1598,23,55,2013-12-25T23:00:00Z
105945,2013,12,25,2357.0,2359,-2.0,446.0,445,1.0,B6,745,N636JB,JFK,PSE,204.0,1617,23,59,2013-12-25T23:00:00Z
105946,2013,12,25,2357.0,2359,-2.0,433.0,437,-4.0,B6,839,N784JB,JFK,BQN,194.0,1576,23,59,2013-12-25T23:00:00Z
105947,2013,12,25,NaN,1630,NaN,NaN,1838,NaN,DL,2231,N312US,LGA,DTW,NaN,502,16,30,2013-12-25T16:00:00Z
105948,2013,12,25,NaN,1525,NaN,NaN,1720,NaN,MQ,2840,N8EGMQ,LGA,STL,NaN,888,15,25,2013-12-25T15:00:00Z
105949,2013,12,25,NaN,1100,NaN,NaN,1210,NaN,MQ,3230,N524MQ,JFK,DCA,NaN,213,11,0,2013-12-25T11:00:00Z
105950,2013,12,25,NaN,1930,NaN,NaN,2115,NaN,MQ,3535,N509MQ,JFK,CMH,NaN,483,19,30,2013-12-25T19:00:00Z

In [96]:
nycflights[["carrier", "dep_delay", "arr_delay"]]
nycflights.assign(recoup = nycflights.arr_delay - nycflights.dep_delay)

KeyError: "['recoup'] not in index"